# Generated by Django 5.2.7 on 2025-11-10 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpolls', '0002_alter_quickpoll_creator'),
        ('students', '0005_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quickpolls.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quickpolls.quickpoll')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='students.student')),
            ],
        ),
    ]
