# Generated by Django 5.2.7 on 2025-11-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickpolls', '0003_pollvote'),
        ('students', '0006_studenttoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'student')},
        ),
    ]
