# Generated by Django 5.2.7 on 2025-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpolls', '0004_alter_pollvote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickpoll',
            name='name',
            field=models.CharField(db_index=True, default='Untitled Poll', max_length=120),
            preserve_default=False,
        ),
    ]
